### ISSUE TITLE
An incorrect contract code got "Verified" in explorer

### ISSUE THREAD

**Issue by FrancoCRO** [crypto-org-chain/cronos-blockscout#35]
A non-WETH token Contract was deployed to Cronos Testnet. The explore somehow accepting wrong solidity code
https://cronos.crypto.org/explorer/testnet3/address/0x1E66e48DCA96eDc2BEB980a0CC3bd1c578BDf1cF/contracts

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System: Mac OS
* Blockscout Version/branch: 

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour
Explorer should reject WETH9 contract 

### Actual behaviour
Explorer accepted the contract and mark the contract as verified

**Comment by WilliamXieCrypto** [comment]
This seems to happen randomly, I can reproduce this like: https://cronos.crypto.org/explorer/testnet3/address/0xdd6FcF63fF1A51bf10AFea67252D493dD5818837/contracts verified with different contract code.

**Comment by WilliamXieCrypto** [comment]
After tested the new version of Blockscout can not reproduce this issue.

**Comment by WilliamXieCrypto** [comment]
This issue will be closed and will be reopened if it reappears.
