### ISSUE TITLE
url for displaying token details is not correct 

### ISSUE THREAD

**Issue by jason-wong-crypto** [crypto-org-chain/cronos-blockscout#36]
url for displaying token details is not correct when integrating with metamask.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System: N/A

* Blockscout Version/branch: current version in testnet3 explorer

### Steps to reproduce

1. add cronos testnet3 to metamask (with explorer link = https://cronos.crypto.org/explorer/testnet3/)
2. add a token for tracking (e.g. 0x1E66e48DCA96eDc2BEB980a0CC3bd1c578BDf1cF)
3. select the token and click "view asset on explorer"
4. this [link](https://cronos.crypto.org/explorer/testnet3/token/0x1E66e48DCA96eDc2BEB980a0CC3bd1c578BDf1cF) show up and **`page not found`** shown
<img width="419" alt="Screenshot 2021-11-02 at 5 22 37 PM" src="https://user-images.githubusercontent.com/57336769/139829877-ebb1e881-bc9b-4d13-98e3-39c7e78a1bd9.png">
<img width="365" alt="Screenshot 2021-11-02 at 5 26 57 PM" src="https://user-images.githubusercontent.com/57336769/139830031-6e7b04c7-73c7-464c-ac5a-33bff4214b0e.png">

### Expected behaviour
that [link](https://cronos.crypto.org/explorer/testnet3/token/0x1E66e48DCA96eDc2BEB980a0CC3bd1c578BDf1cF) should show the token details like transaction history, total supply ...
[content to be displayed](https://cronos.crypto.org/explorer/testnet3/token/0x1E66e48DCA96eDc2BEB980a0CC3bd1c578BDf1cF) 

### Actual behaviour
this [link](https://cronos.crypto.org/explorer/testnet3/token/0x1E66e48DCA96eDc2BEB980a0CC3bd1c578BDf1cF) show up and page not found shown

**Comment by WilliamXieCrypto** [comment]
@jason-wong-crypto  This issue has been fixed in production, testnet3 will be updated later.
