### ISSUE TITLE
Wrong Gas Limit

### ISSUE THREAD

**Issue by crypto-facs** [crypto-org-chain/cronos-blockscout#41]
Inconsistency with Gas Limit

![image](https://user-images.githubusercontent.com/84574577/140781599-9152a942-134a-4627-99b9-31d34ad6eb8f.png)

**Comment by WilliamXieCrypto** [comment]
@crypto-facs @tomtau After debug and analysis, we found that this is the result returned from the JSON RPC API: 
![image](https://user-images.githubusercontent.com/87299790/141715108-9d2dced3-6975-4b10-a6dc-c98a65cb0a05.png)
Same block number but return difference gas_limit:
```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x1038B", false],"id":1}' -H "Content-Type: application/json" https://evm-cronos.crypto.org
```

**Comment by thomas-nguy** [comment]
open issue there https://github.com/tharsis/ethermint/issues/747

**Comment by WilliamXieCrypto** [comment]
Because this issues is coming from ethermint, now close this issues.

**Comment by crypto-facs** [comment]
Should be fixed by this https://github.com/tharsis/ethermint/pull/782
