### ISSUE TITLE
Problem: Contracts verification returns incorrect byte code mismatch and compiler mismatch error

### ISSUE THREAD

**Issue by WilliamXieCrypto** [crypto-org-chain/cronos-blockscout#54]
Contracts verification returns incorrect byte code mismatch and compiler mismatch error.

**Comment by WilliamXieCrypto** [comment]
In general, "incorrect byte code..." is that you are using a different code than the deployed contract to verify. The compiler mismatch cause you using a different version with your contract code which you try to verify one.

**Comment by WilliamXieCrypto** [comment]
CronosCRC20 FYI: https://cronos.crypto.org/explorer/address/0x3C9E6b24a3284bbBDdb8b5a4537888E571E940FC/contracts

**Comment by crypto-facs** [comment]
ok I am testing locally and I have been able to verify multpiple contracts with our latest internal version. I am seeing an error on the VVSFActory [contract](https://cronos.crypto.org/explorer/address/0x2D03bECE6747ADC00E1a131BBA1469C15fD11e03/contracts) when I try to verify it. I am getting the following error


```2021-12-01T19:14:38.979` application=explorer [warn] There was an error compiling a provided contract: {:error, [%{"component" => "general", "formattedMessage" => "New.sol:152:24: TypeError: The \"chainid\" instruction is only available for Istanbul-compatible VMs  (you are currently compiling for \"petersburg\").\n            chainId := chainid\r\n                       ^-----^\n", "message" => "The \"chainid\" instruction is only available for Istanbul-compatible VMs  (you are currently compiling for \"petersburg\").", "severity" => "error", "sourceLocation" => %{"end" => 6072, "file" => "New.sol", "start" => 6065}, "type" => "TypeError"}]```

**Comment by WilliamXieCrypto** [comment]
@crypto-facs I've successfully validated it [LINK](https://cronos.3ona.co/explorer/address/0x690F98FB68fd9f73D97D5b9667eA725513f2E85f/contracts), not sure if we are the same code?

**Comment by crypto-facs** [comment]
Thanks to @WilliamXieCrypto and @mofhusseini investigation we have found that the contract verification issues are not on blockscout side.
