### ISSUE TITLE
Transactions CSV Export does not work

### ISSUE THREAD

**Issue by RudolfAchter** [crypto-org-chain/cronos-blockscout#82]
*Describe your issue here.*

I am trying to export the transaction of my Cronos Address via
https://cronos.org/explorer/csv-export?address=MyAddress&type=transactions

as CSV.
After setting Date and clicking on "Download" nothing happens. Instead i see errors in Edge Browser Dev Console

```text
csv-export:1 
        
       Refused to load the script 'https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://ajax.cloudflare.com https://coinzillatag.com". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

datepicker-5cfde591f010b716b0d9b0ba12bc4bcf.js?vsn=d:2 
        
       Uncaught ReferenceError: grecaptcha is not defined
    at HTMLButtonElement.<anonymous> (datepicker-5cfde591f010b716b0d9b0ba12bc4bcf.js:2:189192)
    at HTMLButtonElement.dispatch (datepicker-5cfde591f010b716b0d9b0ba12bc4bcf.js:2:56027)
    at HTMLButtonElement.y.handle (datepicker-5cfde591f010b716b0d9b0ba12bc4bcf.js:2:54022)
```

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System: Windows 10
* Blockscout Version/branch: Live Website at https://cronos.org/

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

- Use Microsoft Edge on Windows 10 (but other Browsers of mine have the same issue)
- Go to https://cronos.org/explorer/csv-export?address=YourWalletAddressHere&type=transactions
- Try to download your Transactions

### Expected behaviour

*Tell us what should happen.*

It should give me a CSV of chosen timeframe

### Actual behaviour

*Tell us what happens instead.*

nothing happens. Instead Error Messages in Dev Console. Seems like Browser Security Policies Block some Scripts. But my Browser Settings are default.

![image](https://user-images.githubusercontent.com/56109433/160274088-b43a4ed3-5e19-4598-bb15-bae084f546a6.png)

**Comment by mofhusseini** [comment]
@RudolfAchter issue is fixed now
